Entities:
  - name: suzanne
    transform:
      position: [0, 0, 0]
    components:
      - id: MeshRenderer
        model: test1.obj
        instance: test_rock
  - name: "cam1"
    transform:
      position: [0.0, 0.0, 10.0]
    components:
      - id: "Camera"
        main: true
      - id: "TestController"
  - name: "cam2"
    transform:
      position: [0.0, 5.0, 10.0]
    components:
      - id: "Camera"
        main: false
      - id: "TestController"
        enabled: false
  - name: "orchestrator"
    components:
      - id: "CameraOrchestrator"
