Shaders:
  - name: test
    vert: simple_vert
    frag: simple_frag

ShaderInstances:
  - name: test
    diffusePath: diffuse.png

Meshes:
  - test1

Entities:
  - name: "cam"
    transform:
      position: [0.0, 0.0, 10.0]
    components:
      - id: "Camera"
        main: true
      - id: "TestController"
