Meshes:
  - test1.obj

Entities:
  - name: "cam1"
    transform:
      position: [0.0, 0.0, 10.0]
    components:
      - id: "Camera"
        main: true
      - id: "TestController"
  - name: "cam2"
    transform:
      position: [0.0, 5.0, 10.0]
    components:
      - id: "Camera"
        main: false
      - id: "TestController"
        enabled: false
  - name: "orchestrator"
    components:
      - id: "CameraOrchestrator"
