Shaders:
  - name: Test
    vertName: vert
    fragName: frag

ShaderInstances:
  - name: test
    diffusePath: diffuse.png

Meshes:
  - test1

Entites:
  - transform:
      {
        x: 0.0,
        y: 0.0,
        z: 0.0,
        xAngle: 0.0,
        yAngle: 0.0,
        zAngle: 0.0,
        xScale: 1.0,
        yScale: 1.0,
        zScale: 1.0,
      }
    graphics:
      mesh: test1
      material: test
    scripts:
      - scriptId: test
        params: ["test", 1, false]
